package config

const (
	AGGREGATE_START_VERSION       = -1
	CHANGES_EVENT_CAPAPACITY      = 50
	EVENT_STORE_CONNECTION_STRING = "EVENT_STORE_CONNECTION_STRING"
	MONGO_DB_URI                  = "MONGO_DB_URI"
)
